# Application of Deep Neural Network for Twitter Data

In [1]:
#For this project we will only use panda and numpy
import pandas as pd
import numpy as np
import tensorflow as tf

C:\Users\pnkum\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
#This is one time thing, where we will download that data from online
df = pd.read_csv("C:/Users/pnkum/Desktop/Projects/NLP/Praveen/Always_Concrete.csv", encoding="latin-1")
df.shape

(2392, 1229)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2392 entries, 0 to 2391
Columns: 1229 entries, ATUSER to class
dtypes: float64(9), int64(1220)
memory usage: 22.4 MB


In [4]:
df["class"].value_counts()

1    1196
2    1196
Name: class, dtype: int64

In [5]:
features = list(df.columns[1:1228])

In [6]:
target = df.columns[1228:1229]

In [7]:
#Now we need to separate the data into feature data and target data
X = df[features] #our features that we will use to predict Y
Y = df[target] #our dependent variable, the one we are trying to predict from X

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state=42)

In [9]:
config = tf.contrib.learn.RunConfig(tf_random_seed=42) # not shown in the config

feature_cols = tf.contrib.learn.infer_real_valued_columns_from_input(X_train)
dnn_clf = tf.contrib.learn.DNNClassifier(hidden_units=[300,100], n_classes =20,
                                         feature_columns=feature_cols, config=config)
dnn_clf = tf.contrib.learn.SKCompat(dnn_clf) # if TensorFlow >= 1.1
dnn_clf.fit(X_train, y_train, batch_size=50, steps=40000)

Instructions for updating:
Use the retry module or similar alternatives.
Instructions for updating:
When switching to tf.estimator.Estimator, use tf.estimator.RunConfig instead.
Instructions for updating:
Please specify feature columns explicitly.
Instructions for updating:
Please use tensorflow/transform or tf.data.
Instructions for updating:
Please feed input to tf.data to support dask.
Instructions for updating:
Please access pandas data directly.
Instructions for updating:
Please use tensorflow/transform or tf.data.
Instructions for updating:
Please convert numpy dtypes explicitly.
Instructions for updating:
Please specify feature columns explicitly.
Instructions for updating:
Please switch to tf.contrib.estimator.*_head.
Instructions for updating:
Please replace uses of any Estimator from tf.contrib.learn with an Estimator from tf.estimator.*
INFO:tensorflow:Using config: {'_task_type': None, '_task_id': 0, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object

INFO:tensorflow:loss = 0.00096558477, step = 1901 (0.355 sec)
INFO:tensorflow:global_step/sec: 285.76
INFO:tensorflow:loss = 0.0009294243, step = 2001 (0.349 sec)
INFO:tensorflow:global_step/sec: 287.832
INFO:tensorflow:loss = 0.00071428926, step = 2101 (0.347 sec)
INFO:tensorflow:global_step/sec: 289.492
INFO:tensorflow:loss = 0.00070522586, step = 2201 (0.345 sec)
INFO:tensorflow:global_step/sec: 283.739
INFO:tensorflow:loss = 0.132587, step = 2301 (0.352 sec)
INFO:tensorflow:global_step/sec: 284.954
INFO:tensorflow:loss = 0.009992181, step = 2401 (0.351 sec)
INFO:tensorflow:global_step/sec: 284.644
INFO:tensorflow:loss = 0.007849272, step = 2501 (0.351 sec)
INFO:tensorflow:global_step/sec: 286.182
INFO:tensorflow:loss = 0.0034495979, step = 2601 (0.349 sec)
INFO:tensorflow:global_step/sec: 289.504
INFO:tensorflow:loss = 0.0023716127, step = 2701 (0.345 sec)
INFO:tensorflow:global_step/sec: 284.954
INFO:tensorflow:loss = 0.0034084308, step = 2801 (0.351 sec)
INFO:tensorflow:global_st

INFO:tensorflow:global_step/sec: 283.335
INFO:tensorflow:loss = 0.00019586936, step = 10001 (0.353 sec)
INFO:tensorflow:global_step/sec: 289.495
INFO:tensorflow:loss = 0.00021049006, step = 10101 (0.345 sec)
INFO:tensorflow:global_step/sec: 287.833
INFO:tensorflow:loss = 0.00014461466, step = 10201 (0.347 sec)
INFO:tensorflow:global_step/sec: 258.35
INFO:tensorflow:loss = 0.00012473368, step = 10301 (0.388 sec)
INFO:tensorflow:global_step/sec: 232.992
INFO:tensorflow:loss = 0.00016346555, step = 10401 (0.429 sec)
INFO:tensorflow:global_step/sec: 236.056
INFO:tensorflow:loss = 0.0002558648, step = 10501 (0.423 sec)
INFO:tensorflow:global_step/sec: 242.947
INFO:tensorflow:loss = 0.00020178844, step = 10601 (0.412 sec)
INFO:tensorflow:global_step/sec: 255.069
INFO:tensorflow:loss = 0.0003070982, step = 10701 (0.392 sec)
INFO:tensorflow:global_step/sec: 260.748
INFO:tensorflow:loss = 0.000118464464, step = 10801 (0.383 sec)
INFO:tensorflow:global_step/sec: 259.05
INFO:tensorflow:loss = 0.0

INFO:tensorflow:loss = 3.1800068e-05, step = 17901 (0.354 sec)
INFO:tensorflow:global_step/sec: 287.417
INFO:tensorflow:loss = 6.539709e-05, step = 18001 (0.347 sec)
INFO:tensorflow:global_step/sec: 289.504
INFO:tensorflow:loss = 6.501034e-05, step = 18101 (0.345 sec)
INFO:tensorflow:global_step/sec: 289.924
INFO:tensorflow:loss = 4.9836424e-05, step = 18201 (0.345 sec)
INFO:tensorflow:global_step/sec: 290.332
INFO:tensorflow:loss = 3.6261146e-05, step = 18301 (0.345 sec)
INFO:tensorflow:global_step/sec: 289.503
INFO:tensorflow:loss = 0.0001136654, step = 18401 (0.345 sec)
INFO:tensorflow:global_step/sec: 286.18
INFO:tensorflow:loss = 4.2950564e-05, step = 18501 (0.349 sec)
INFO:tensorflow:global_step/sec: 286.993
INFO:tensorflow:loss = 7.652153e-05, step = 18601 (0.348 sec)
INFO:tensorflow:global_step/sec: 289.054
INFO:tensorflow:loss = 5.3093907e-05, step = 18701 (0.346 sec)
INFO:tensorflow:global_step/sec: 263.498
INFO:tensorflow:loss = 5.822258e-05, step = 18801 (0.381 sec)
INFO:te

INFO:tensorflow:global_step/sec: 284.131
INFO:tensorflow:loss = 3.227925e-05, step = 25901 (0.352 sec)
INFO:tensorflow:global_step/sec: 285.77
INFO:tensorflow:loss = 4.169837e-05, step = 26001 (0.350 sec)
INFO:tensorflow:global_step/sec: 290.76
INFO:tensorflow:loss = 2.6477377e-05, step = 26101 (0.344 sec)
INFO:tensorflow:global_step/sec: 287.005
INFO:tensorflow:loss = 4.0093233e-05, step = 26201 (0.348 sec)
INFO:tensorflow:global_step/sec: 290.744
INFO:tensorflow:loss = 2.7967302e-05, step = 26301 (0.344 sec)
INFO:tensorflow:global_step/sec: 289.913
INFO:tensorflow:loss = 2.3239767e-05, step = 26401 (0.345 sec)
INFO:tensorflow:global_step/sec: 288.996
INFO:tensorflow:loss = 2.254606e-05, step = 26501 (0.346 sec)
INFO:tensorflow:global_step/sec: 284.142
INFO:tensorflow:loss = 7.2903305e-05, step = 26601 (0.352 sec)
INFO:tensorflow:global_step/sec: 287.417
INFO:tensorflow:loss = 3.2969256e-05, step = 26701 (0.348 sec)
INFO:tensorflow:global_step/sec: 289.505
INFO:tensorflow:loss = 3.123

INFO:tensorflow:loss = 2.6312759e-05, step = 33801 (0.356 sec)
INFO:tensorflow:global_step/sec: 282.934
INFO:tensorflow:loss = 0.010036385, step = 33901 (0.353 sec)
INFO:tensorflow:global_step/sec: 278.976
INFO:tensorflow:loss = 1.5348936e-05, step = 34001 (0.358 sec)
INFO:tensorflow:global_step/sec: 281.734
INFO:tensorflow:loss = 0.0215578, step = 34101 (0.355 sec)
INFO:tensorflow:global_step/sec: 279.366
INFO:tensorflow:loss = 3.1013045e-05, step = 34201 (0.358 sec)
INFO:tensorflow:global_step/sec: 282.934
INFO:tensorflow:loss = 2.7507262e-05, step = 34301 (0.353 sec)
INFO:tensorflow:global_step/sec: 255.4
INFO:tensorflow:loss = 4.8291506e-05, step = 34401 (0.392 sec)
INFO:tensorflow:global_step/sec: 258.045
INFO:tensorflow:loss = 2.4679559e-05, step = 34501 (0.387 sec)
INFO:tensorflow:global_step/sec: 258.713
INFO:tensorflow:loss = 3.258797e-05, step = 34601 (0.387 sec)
INFO:tensorflow:global_step/sec: 284.548
INFO:tensorflow:loss = 3.3756754e-05, step = 34701 (0.351 sec)
INFO:tenso

SKCompat()

In [10]:
from sklearn.metrics import cohen_kappa_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_recall_fscore_support
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

y_pred = dnn_clf.predict(X_test)
accuracy_score(y_test, y_pred['classes'])

INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\pnkum\AppData\Local\Temp\tmp05aqcvhf\model.ckpt-40000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


0.8935281837160751

In [11]:
recall_score(y_test, y_pred['classes'], average='micro')

0.8935281837160751

In [12]:
precision_score(y_test, y_pred['classes'], average='micro')

0.8935281837160751

In [13]:
cohen_kappa_score(y_test, y_pred['classes'])

0.7854564615992623

In [14]:
precision_recall_fscore_support(y_test, y_pred['classes'])

(array([0.87732342, 0.91428571]),
 array([0.92913386, 0.85333333]),
 array([0.90248566, 0.88275862]),
 array([254, 225], dtype=int64))