# Application of Deep Neural Network for Twitter Data

In [1]:
#For this project we will only use panda and numpy
import pandas as pd
import numpy as np
import tensorflow as tf

C:\Users\pnkum\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
#This is one time thing, where we will download that data from online
df = pd.read_csv("C:/Users/pnkum/Desktop/Projects/tweetdata/All Data/TML_Concrete.csv", encoding="latin-1")
df.shape

(9264, 1230)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9264 entries, 0 to 9263
Columns: 1230 entries, ATUSER to class
dtypes: float64(9), int64(1221)
memory usage: 86.9 MB


In [4]:
df["class"].value_counts()

2    3088
1    3088
0    3088
Name: class, dtype: int64

In [5]:
features = list(df.columns[1:1229])

In [6]:
target = df.columns[1229:1230]

In [7]:
#Now we need to separate the data into feature data and target data
X = df[features] #our features that we will use to predict Y
Y = df[target] #our dependent variable, the one we are trying to predict from X

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state=42)

In [9]:
config = tf.contrib.learn.RunConfig(tf_random_seed=42) # not shown in the config

feature_cols = tf.contrib.learn.infer_real_valued_columns_from_input(X_train)
dnn_clf = tf.contrib.learn.DNNClassifier(hidden_units=[300,100], n_classes =20,
                                         feature_columns=feature_cols, config=config)
dnn_clf = tf.contrib.learn.SKCompat(dnn_clf) # if TensorFlow >= 1.1
dnn_clf.fit(X_train, y_train, batch_size=50, steps=40000)

Instructions for updating:
Use the retry module or similar alternatives.
Instructions for updating:
When switching to tf.estimator.Estimator, use tf.estimator.RunConfig instead.
Instructions for updating:
Please specify feature columns explicitly.
Instructions for updating:
Please use tensorflow/transform or tf.data.
Instructions for updating:
Please feed input to tf.data to support dask.
Instructions for updating:
Please access pandas data directly.
Instructions for updating:
Please use tensorflow/transform or tf.data.
Instructions for updating:
Please convert numpy dtypes explicitly.
Instructions for updating:
Please specify feature columns explicitly.
Instructions for updating:
Please switch to tf.contrib.estimator.*_head.
Instructions for updating:
Please replace uses of any Estimator from tf.contrib.learn with an Estimator from tf.estimator.*
INFO:tensorflow:Using config: {'_task_type': None, '_task_id': 0, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object

INFO:tensorflow:loss = 0.014788556, step = 1901 (0.393 sec)
INFO:tensorflow:global_step/sec: 280.152
INFO:tensorflow:loss = 0.015300871, step = 2001 (0.356 sec)
INFO:tensorflow:global_step/sec: 282.133
INFO:tensorflow:loss = 0.058321208, step = 2101 (0.354 sec)
INFO:tensorflow:global_step/sec: 289.505
INFO:tensorflow:loss = 0.13291726, step = 2201 (0.345 sec)
INFO:tensorflow:global_step/sec: 285.771
INFO:tensorflow:loss = 0.09257544, step = 2301 (0.350 sec)
INFO:tensorflow:global_step/sec: 276.655
INFO:tensorflow:loss = 0.13222922, step = 2401 (0.361 sec)
INFO:tensorflow:global_step/sec: 287.004
INFO:tensorflow:loss = 0.06441533, step = 2501 (0.348 sec)
INFO:tensorflow:global_step/sec: 285.762
INFO:tensorflow:loss = 0.09195559, step = 2601 (0.349 sec)
INFO:tensorflow:global_step/sec: 290.347
INFO:tensorflow:loss = 0.15969628, step = 2701 (0.345 sec)
INFO:tensorflow:global_step/sec: 288.249
INFO:tensorflow:loss = 0.19143663, step = 2801 (0.346 sec)
INFO:tensorflow:global_step/sec: 286.8

INFO:tensorflow:loss = 0.061527234, step = 10101 (0.347 sec)
INFO:tensorflow:global_step/sec: 288.249
INFO:tensorflow:loss = 0.06694177, step = 10201 (0.347 sec)
INFO:tensorflow:global_step/sec: 288.654
INFO:tensorflow:loss = 0.014070442, step = 10301 (0.347 sec)
INFO:tensorflow:global_step/sec: 286.181
INFO:tensorflow:loss = 0.020451488, step = 10401 (0.349 sec)
INFO:tensorflow:global_step/sec: 285.771
INFO:tensorflow:loss = 0.05780865, step = 10501 (0.350 sec)
INFO:tensorflow:global_step/sec: 279.367
INFO:tensorflow:loss = 0.024268102, step = 10601 (0.358 sec)
INFO:tensorflow:global_step/sec: 276.878
INFO:tensorflow:loss = 0.1131522, step = 10701 (0.361 sec)
INFO:tensorflow:global_step/sec: 248.404
INFO:tensorflow:loss = 0.0890023, step = 10801 (0.403 sec)
INFO:tensorflow:global_step/sec: 260.402
INFO:tensorflow:loss = 0.08510703, step = 10901 (0.384 sec)
INFO:tensorflow:global_step/sec: 268.825
INFO:tensorflow:loss = 0.010633993, step = 11001 (0.372 sec)
INFO:tensorflow:global_step/

INFO:tensorflow:loss = 0.06384665, step = 18201 (0.360 sec)
INFO:tensorflow:global_step/sec: 276.251
INFO:tensorflow:loss = 0.13097474, step = 18301 (0.362 sec)
INFO:tensorflow:global_step/sec: 280.545
INFO:tensorflow:loss = 0.09700083, step = 18401 (0.356 sec)
INFO:tensorflow:global_step/sec: 284.143
INFO:tensorflow:loss = 0.14567962, step = 18501 (0.352 sec)
INFO:tensorflow:global_step/sec: 279.352
INFO:tensorflow:loss = 0.09805851, step = 18601 (0.358 sec)
INFO:tensorflow:global_step/sec: 277.04
INFO:tensorflow:loss = 0.06636746, step = 18701 (0.361 sec)
INFO:tensorflow:global_step/sec: 288.665
INFO:tensorflow:loss = 0.031562455, step = 18801 (0.346 sec)
INFO:tensorflow:global_step/sec: 289.084
INFO:tensorflow:loss = 0.18525204, step = 18901 (0.346 sec)
INFO:tensorflow:global_step/sec: 287.005
INFO:tensorflow:loss = 0.056386307, step = 19001 (0.348 sec)
INFO:tensorflow:global_step/sec: 282.533
INFO:tensorflow:loss = 0.024731643, step = 19101 (0.354 sec)
INFO:tensorflow:global_step/s

INFO:tensorflow:loss = 0.052398294, step = 26301 (0.353 sec)
INFO:tensorflow:global_step/sec: 279.759
INFO:tensorflow:loss = 0.06349921, step = 26401 (0.357 sec)
INFO:tensorflow:global_step/sec: 269.188
INFO:tensorflow:loss = 0.1277638, step = 26501 (0.372 sec)
INFO:tensorflow:global_step/sec: 277.423
INFO:tensorflow:loss = 0.020170815, step = 26601 (0.360 sec)
INFO:tensorflow:global_step/sec: 280.547
INFO:tensorflow:loss = 0.1390043, step = 26701 (0.357 sec)
INFO:tensorflow:global_step/sec: 278.197
INFO:tensorflow:loss = 0.10323862, step = 26801 (0.359 sec)
INFO:tensorflow:global_step/sec: 285.363
INFO:tensorflow:loss = 0.09777176, step = 26901 (0.350 sec)
INFO:tensorflow:global_step/sec: 285.77
INFO:tensorflow:loss = 0.09594648, step = 27001 (0.350 sec)
INFO:tensorflow:global_step/sec: 288.666
INFO:tensorflow:loss = 0.054858305, step = 27101 (0.346 sec)
INFO:tensorflow:global_step/sec: 284.954
INFO:tensorflow:loss = 0.053338252, step = 27201 (0.351 sec)
INFO:tensorflow:global_step/se

INFO:tensorflow:loss = 0.062360946, step = 34401 (0.353 sec)
INFO:tensorflow:global_step/sec: 282.134
INFO:tensorflow:loss = 0.058335003, step = 34501 (0.355 sec)
INFO:tensorflow:global_step/sec: 282.532
INFO:tensorflow:loss = 0.06367856, step = 34601 (0.354 sec)
INFO:tensorflow:global_step/sec: 282.533
INFO:tensorflow:loss = 0.100770295, step = 34701 (0.353 sec)
INFO:tensorflow:global_step/sec: 289.504
INFO:tensorflow:loss = 0.008337368, step = 34801 (0.345 sec)
INFO:tensorflow:global_step/sec: 287.418
INFO:tensorflow:loss = 0.13996872, step = 34901 (0.347 sec)
INFO:tensorflow:global_step/sec: 280.94
INFO:tensorflow:loss = 0.13028719, step = 35001 (0.356 sec)
INFO:tensorflow:global_step/sec: 279.76
INFO:tensorflow:loss = 0.024596399, step = 35101 (0.357 sec)
INFO:tensorflow:global_step/sec: 276.655
INFO:tensorflow:loss = 0.055182718, step = 35201 (0.361 sec)
INFO:tensorflow:global_step/sec: 280.151
INFO:tensorflow:loss = 0.016841741, step = 35301 (0.357 sec)
INFO:tensorflow:global_ste

SKCompat()

In [10]:
from sklearn.metrics import cohen_kappa_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_recall_fscore_support
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

y_pred = dnn_clf.predict(X_test)
accuracy_score(y_test, y_pred['classes'])

INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\pnkum\AppData\Local\Temp\tmphr_98614\model.ckpt-40000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


0.9638424177010254

In [11]:
cohen_kappa_score(y_test, y_pred['classes'])

0.9457228982820769

In [12]:
precision_recall_fscore_support(y_test, y_pred['classes'])

(array([0.93108504, 0.96610169, 1.        ]),
 array([1.        , 0.92833876, 0.96192053]),
 array([0.96431283, 0.94684385, 0.98059072]),
 array([635, 614, 604], dtype=int64))

In [13]:
precision_score(y_test, y_pred['classes'], average='micro')

0.9638424177010254

In [14]:
recall_score(y_test, y_pred['classes'], average='micro')

0.9638424177010254