# Application of Deep Neural Network for Twitter Data

In [1]:
#For this project we will only use panda and numpy
import pandas as pd
import numpy as np
import tensorflow as tf

C:\Users\pnkum\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
#This is one time thing, where we will download that data from online
df = pd.read_csv("C:/Users/pnkum/Desktop/Projects/tweetdata/All Data/ISIS_Concrete.csv", encoding="latin-1")
df.shape

(4608, 1225)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4608 entries, 0 to 4607
Columns: 1225 entries, ATUSER to class
dtypes: float64(9), int64(1216)
memory usage: 43.1 MB


In [4]:
df["class"].value_counts()

2    1536
1    1536
0    1536
Name: class, dtype: int64

In [5]:
features = list(df.columns[1:1225])

In [6]:
target = df.columns[1224:1225]

In [7]:
#Now we need to separate the data into feature data and target data
X = df[features] #our features that we will use to predict Y
Y = df[target] #our dependent variable, the one we are trying to predict from X

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state=42)

In [9]:
config = tf.contrib.learn.RunConfig(tf_random_seed=42) # not shown in the config

feature_cols = tf.contrib.learn.infer_real_valued_columns_from_input(X_train)
dnn_clf = tf.contrib.learn.DNNClassifier(hidden_units=[300,100], n_classes =10,
                                         feature_columns=feature_cols, config=config)
dnn_clf = tf.contrib.learn.SKCompat(dnn_clf) # if TensorFlow >= 1.1
dnn_clf.fit(X_train, y_train, batch_size=50, steps=40000)

Instructions for updating:
Use the retry module or similar alternatives.
Instructions for updating:
When switching to tf.estimator.Estimator, use tf.estimator.RunConfig instead.
Instructions for updating:
Please specify feature columns explicitly.
Instructions for updating:
Please use tensorflow/transform or tf.data.
Instructions for updating:
Please feed input to tf.data to support dask.
Instructions for updating:
Please access pandas data directly.
Instructions for updating:
Please use tensorflow/transform or tf.data.
Instructions for updating:
Please convert numpy dtypes explicitly.
Instructions for updating:
Please specify feature columns explicitly.
Instructions for updating:
Please switch to tf.contrib.estimator.*_head.
Instructions for updating:
Please replace uses of any Estimator from tf.contrib.learn with an Estimator from tf.estimator.*
INFO:tensorflow:Using config: {'_task_type': None, '_task_id': 0, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object

INFO:tensorflow:global_step/sec: 277.424
INFO:tensorflow:loss = 0.0003570749, step = 1901 (0.360 sec)
INFO:tensorflow:global_step/sec: 289.234
INFO:tensorflow:loss = 0.0004347726, step = 2001 (0.346 sec)
INFO:tensorflow:global_step/sec: 274.357
INFO:tensorflow:loss = 0.00028409364, step = 2101 (0.365 sec)
INFO:tensorflow:global_step/sec: 250.275
INFO:tensorflow:loss = 0.0002551689, step = 2201 (0.399 sec)
INFO:tensorflow:global_step/sec: 255.729
INFO:tensorflow:loss = 0.00027977274, step = 2301 (0.391 sec)
INFO:tensorflow:global_step/sec: 267.025
INFO:tensorflow:loss = 0.00026159166, step = 2401 (0.374 sec)
INFO:tensorflow:global_step/sec: 286.592
INFO:tensorflow:loss = 0.00018043163, step = 2501 (0.349 sec)
INFO:tensorflow:global_step/sec: 288.666
INFO:tensorflow:loss = 0.00017281208, step = 2601 (0.346 sec)
INFO:tensorflow:global_step/sec: 287.833
INFO:tensorflow:loss = 0.00025181743, step = 2701 (0.347 sec)
INFO:tensorflow:global_step/sec: 284.547
INFO:tensorflow:loss = 0.0001503886

INFO:tensorflow:global_step/sec: 283.336
INFO:tensorflow:loss = 8.085889e-05, step = 9901 (0.353 sec)
INFO:tensorflow:global_step/sec: 287.831
INFO:tensorflow:loss = 4.345747e-05, step = 10001 (0.348 sec)
INFO:tensorflow:global_step/sec: 284.144
INFO:tensorflow:loss = 3.6303234e-05, step = 10101 (0.351 sec)
INFO:tensorflow:global_step/sec: 288.249
INFO:tensorflow:loss = 3.326208e-05, step = 10201 (0.347 sec)
INFO:tensorflow:global_step/sec: 290.347
INFO:tensorflow:loss = 3.1906817e-05, step = 10301 (0.344 sec)
INFO:tensorflow:global_step/sec: 284.953
INFO:tensorflow:loss = 4.3540127e-05, step = 10401 (0.351 sec)
INFO:tensorflow:global_step/sec: 289.504
INFO:tensorflow:loss = 4.9675655e-05, step = 10501 (0.345 sec)
INFO:tensorflow:global_step/sec: 286.592
INFO:tensorflow:loss = 7.215114e-05, step = 10601 (0.349 sec)
INFO:tensorflow:global_step/sec: 285.771
INFO:tensorflow:loss = 5.1321764e-05, step = 10701 (0.350 sec)
INFO:tensorflow:global_step/sec: 286.991
INFO:tensorflow:loss = 7.162

INFO:tensorflow:loss = 2.228347e-05, step = 17801 (0.348 sec)
INFO:tensorflow:global_step/sec: 282.133
INFO:tensorflow:loss = 2.9370969e-05, step = 17901 (0.354 sec)
INFO:tensorflow:global_step/sec: 277.424
INFO:tensorflow:loss = 1.7110848e-05, step = 18001 (0.360 sec)
INFO:tensorflow:global_step/sec: 282.934
INFO:tensorflow:loss = 1.3818433e-05, step = 18101 (0.354 sec)
INFO:tensorflow:global_step/sec: 285.362
INFO:tensorflow:loss = 4.4703836e-05, step = 18201 (0.350 sec)
INFO:tensorflow:global_step/sec: 286.181
INFO:tensorflow:loss = 3.089056e-05, step = 18301 (0.349 sec)
INFO:tensorflow:global_step/sec: 286.573
INFO:tensorflow:loss = 5.856705e-05, step = 18401 (0.349 sec)
INFO:tensorflow:global_step/sec: 284.55
INFO:tensorflow:loss = 1.9151672e-05, step = 18501 (0.351 sec)
INFO:tensorflow:global_step/sec: 284.547
INFO:tensorflow:loss = 2.230797e-05, step = 18601 (0.351 sec)
INFO:tensorflow:global_step/sec: 282.519
INFO:tensorflow:loss = 4.652435e-05, step = 18701 (0.354 sec)
INFO:te

INFO:tensorflow:global_step/sec: 281.735
INFO:tensorflow:loss = 3.123065e-05, step = 25801 (0.355 sec)
INFO:tensorflow:global_step/sec: 287.005
INFO:tensorflow:loss = 9.300431e-06, step = 25901 (0.348 sec)
INFO:tensorflow:global_step/sec: 289.504
INFO:tensorflow:loss = 9.977648e-06, step = 26001 (0.345 sec)
INFO:tensorflow:global_step/sec: 284.143
INFO:tensorflow:loss = 4.5442303e-06, step = 26101 (0.352 sec)
INFO:tensorflow:global_step/sec: 285.77
INFO:tensorflow:loss = 1.6819766e-05, step = 26201 (0.349 sec)
INFO:tensorflow:global_step/sec: 287.419
INFO:tensorflow:loss = 1.0976619e-05, step = 26301 (0.348 sec)
INFO:tensorflow:global_step/sec: 285.762
INFO:tensorflow:loss = 1.7929891e-05, step = 26401 (0.350 sec)
INFO:tensorflow:global_step/sec: 287.83
INFO:tensorflow:loss = 9.682008e-06, step = 26501 (0.347 sec)
INFO:tensorflow:global_step/sec: 284.142
INFO:tensorflow:loss = 7.796173e-06, step = 26601 (0.352 sec)
INFO:tensorflow:global_step/sec: 285.771
INFO:tensorflow:loss = 8.71401

INFO:tensorflow:loss = 1.1279397e-05, step = 33701 (0.406 sec)
INFO:tensorflow:global_step/sec: 249.334
INFO:tensorflow:loss = 6.4920587e-06, step = 33801 (0.388 sec)
INFO:tensorflow:global_step/sec: 257.039
INFO:tensorflow:loss = 9.853617e-06, step = 33901 (0.389 sec)
INFO:tensorflow:global_step/sec: 282.132
INFO:tensorflow:loss = 6.8806576e-06, step = 34001 (0.354 sec)
INFO:tensorflow:global_step/sec: 286.182
INFO:tensorflow:loss = 7.734201e-06, step = 34101 (0.349 sec)
INFO:tensorflow:global_step/sec: 285.77
INFO:tensorflow:loss = 1.2811977e-05, step = 34201 (0.350 sec)
INFO:tensorflow:global_step/sec: 282.933
INFO:tensorflow:loss = 1.9173762e-05, step = 34301 (0.353 sec)
INFO:tensorflow:global_step/sec: 287.833
INFO:tensorflow:loss = 2.0729243e-05, step = 34401 (0.347 sec)
INFO:tensorflow:global_step/sec: 288.236
INFO:tensorflow:loss = 3.6763966e-05, step = 34501 (0.347 sec)
INFO:tensorflow:global_step/sec: 286.17
INFO:tensorflow:loss = 8.971452e-06, step = 34601 (0.349 sec)
INFO:t

SKCompat()

In [10]:
from sklearn.metrics import cohen_kappa_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_recall_fscore_support
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

y_pred = dnn_clf.predict(X_test)
accuracy_score(y_test, y_pred['classes'])

INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\pnkum\AppData\Local\Temp\tmp_5vpevjy\model.ckpt-40000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


1.0

In [11]:
cohen_kappa_score(y_test, y_pred['classes'])

1.0

In [12]:
precision_recall_fscore_support(y_test, y_pred['classes'])

(array([1., 1., 1.]),
 array([1., 1., 1.]),
 array([1., 1., 1.]),
 array([331, 300, 291], dtype=int64))

In [13]:
precision_score(y_test, y_pred['classes'], average='micro')

1.0

In [14]:
recall_score(y_test, y_pred['classes'], average='micro')

1.0